constants:
  file:
    upload-directory: D:/student/Spring/upload/item/greengram
    feed-pic: /feed
    profile-pic: /profile
  jwt:
    issuer: green502@green.com
    bearer-format: JWT

    claim-key: signedUser
    secret-key: DaeguGreenArtAcademyClass502MsaClassFightingkkkkkk

    access-token-cookie-name: access-token
    access-token-cookie-path: /
    access-token-cookie-validity-seconds: 900
    access-token-validity-milliseconds: 900_000

    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-path: /api/user/reissue
    refresh-token-cookie-validity-seconds: 1_296_000
    refresh-token-validity-milliseconds: 1_296_000_000

spring:
  application:
    name: greengram
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost/greengram
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: mysql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        format_sql: true
        order_updates: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 15MB
  sql:
    init:
      mode: always

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
